### ISSUE TITLE
Missing relation type in DTD

### ISSUE THREAD

**Issue by fcbr** [globalwordnet/schemas#1]
The following wordnet pointers don't appear to have entries (`relType`) in the DTD:

pointer | string in the wndb2lmf converter
--- | ---
`$` |  `verb_group`
`;u` | `domain_usage`
`-u` | _missing_

**Comment by jmccrae** [comment]
Hi,

verb_group is now 'similar'
domain_usage is now 'exemplifies'
has_domain_usage (-u) is now 'is_examplified_by'

BTW, there is a converter from the WordNet Database format to these schemas:

https://github.com/jmccrae/gwn-scala-api

See the mapping used by this system:

https://github.com/jmccrae/gwn-scala-api/blob/master/src/main/scala/org/globalwordnet/wnapi/wndb.scala#L365
