### ISSUE TITLE
'entails' and 'is_entailed_by' have no definition in ontology

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/schemas#14]
Please check and add a definition.

**Comment by rwingerter55** [comment]
Cf. definition on [github page](http://globalwordnet.github.io/schemas/):

> entails: A verb X entails Y if X cannot be done unles Y is, or has been done.

> is_entailed_by: Opposite of entails

**Comment by rwingerter55** [comment]
Hi John,
 
I saw that you created a file ewn-rels.csv. Google "eurowordnet general 
document",  the pdf file has definitions and much more.
 
If I can help let me know. I could extract definitions from the document.
 
Kind regards
Roland
 
﻿

**Comment by jmccrae** [comment]
I am not really sure what this file does, it was just added as part of the rebasing...

**Comment by rwingerter55** [comment]
EuroWordNet relation types could be valuable (1) as a source of definitions. (2) Because it defines parts-of-speech for which a given relation type can be used. (3) Because it defines tests for many relation types which can be used to determine if the relation applies to a given pair of synsets. 

The relations defined in EuroWordNet overlap with those used in GWA. (The following numbers are based on an exact automatic matching of relation names.) 

1. GWA lists a total of 73 synset relations (including 22 from PWN). 
2. EuroWordNet has a total of 62 relations; it shares 29 with GWA and 1 with PWN.
