### ISSUE TITLE
Definition of 'exemplifies' and 'is_exemplified_by' in ontology

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/schemas#15]
IMO the definition of `exemplifies` is not clear and makes me think of a hyponym/hypernym relation. 

> **exemplifies**
> rdfs:comment
> A relation between two concepts where B is a type of concept A

> **is_exemplified_by**
> rdfs:comment
> A relation between two concepts where A an example of the type B

Cf. also "[example for vs. example of](https://ell.stackexchange.com/questions/191070/example-for-vs-example-of)".

Compare the definitions given on the [github page](http://globalwordnet.github.io/schemas/): 

> exemplifies: Indicates the usage of this word
> is_exemplified_by: Indicates a word involved in the usage described by this word

In order to understand I looked at some examples, e.g. 

> "hence" exemplifies "archaism, archaicism"
> "archaism, archaicism" is_exemplified_by "hence"

IMO this relation would be easier to understand if we put it like this:

`has_example`
A relation between two concepts A and B where A has example B. 

`is_example_for`
A relation between two concepts A and B where A is an example for B.

Example:
"hence" is_example_for "archaism, archaicism"
"archaism, archaicism" has_example "hence"

**Comment by jmccrae** [comment]
'Exemplifies' is a rename of the property that was called `domain_usage` previously. These three domain properties (category, region and usage/exemplifies) indicate a usage label, that is a pragmatic restriction on the use of the word. In the case of 'usage' this primarily meant a usage such as 'archaic' or 'slang'. They basically play the same role as [usage labels](https://www.merriam-webster.com/help/explanatory-notes/dict-usage) in traditional dictionaries.

Perhaps @fcbond can explain the change in name from `domain_usage` to `exemplifies` as I don't remember the motivation for this.

For an improved definition, I would suggest

> ~~A relation between two concepts where Y is a type of concept X. such as idiom, honorific or classifier.~~
> Indicates that the word itself (not the concept it refers to) is an example of a linguistic category such as archaism, slang word, idiom, honorific or trademark

**Comment by jmccrae** [comment]
@fcbond Are you able to comment on this?
