### ISSUE TITLE
wn:is_caused_by and wn:result have identical definition

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/schemas#16]
Both are defined as 

> A   relation between two concepts where concept A comes into existence as a   result of concept B@en

Also, `wn:causes` and `wn:involved_result` share the same definition:

> A   relation between two concepts where concept B comes into existence as a   result of concept A@en

**Comment by jmccrae** [comment]
I'm not really sure there is any difference between these relations. Does anyone else have an opinion?
