### ISSUE TITLE
dc:language metadata

### ISSUE THREAD

**Issue by goodmami** [globalwordnet/schemas#22]
The WN-LMF 1.0 DTD allows 14 of the 15 Dublin Core elements as attributes (setting aside the attribute vs element thing (#5) for a moment) on many LMF elements. The missing one is `dc:language`. Some of the LMF elements have their own `language` attribute, but not all that allow Dublin Core metadata.

Is there a reason for this situation? Can we just add in `dc:language` and use that instead of the default namespace's `language` attribute?

**Comment by jmccrae** [comment]
I think the `language` attribute was introduced in the prior Kyoto-LMF version, so I didn't introduce `dc:language` as this would cause confusion. I think a single property makes more sense overall and we have restrictions on where this property occurs, whereas the DC properties are general metadata properties that can occur anywhere.

**Comment by goodmami** [comment]
My question was answered. I'll close the issue.
