### ISSUE TITLE
Sense key attribute

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/schemas#25]
Do we need a separate attribute for sense keys or is ID sufficent?

**Comment by goodmami** [comment]
If the only purpose is for some kind of compatibility with older resources, would it make sense to distribute this sense-key-to-id mapping as a separate file?

**Comment by jmccrae** [comment]
This could also be an option

**Comment by fcbond** [comment]
I am ok with them being a stand off file.

**Comment by 1313ou** [comment]
I'm rather in favour of a all-in-one XML format (simpler for apps: stripping undesired information is easier than retrieving external info)

**Comment by jmccrae** [comment]
Okay, so I think we will not make any changes here. We should recognize that 'sense keys' are just what Princeton WordNet represents its sense IDs. English WordNet should probably not have created a new schema for sense IDs and will likely switch to using sense keys in the same way as Princeton for the next version. As such, there is no need for a new property we just use `id`

```xml
<LexicalSense id="occultism%1:09:01::">
```

For creating links between sense keys between version (e.g. English -> Princeton) then stand-off files can be used and I don't think we should standardise this at this point. See English WordNet's example:

https://github.com/globalwordnet/english-wordnet/blob/master/src/sensekey-maps.csv

**Comment by goodmami** [comment]
If replacing the current sense IDs with sense keys is on the table and there's some predictable way of creating new ones as the EWN grows, then I'm in favor.

Non-English wordnets don't make use of sense keys to link to PWN, do they?

**Comment by arademaker** [comment]
Not sure if I am following the complete discussion, but let me expose here some ideas we have during the development of our text-based format proposal at https://github.com/own-pt/mill. We have tried some alternatives inspired by the way PWN encodes the adjectives' sense keys. Ideally, I would like to avoid any artificial numeric identifiers like the `lex_id` in the sense keys. 

For `cable_car%1:06:00::` from http://wn.mybluemix.net/synset?id=02934451-n, I would like to replace `car%1:06:04::` with something like `car%1:h/compartment` or similar. That would means, the car sense that is a hyponym of compartment. 

Our hypothesis was that all sense should have at least one relation (or a small set of relations) that discriminate it from the other senses of the same lemma.

**Comment by jmccrae** [comment]
Yes @goodmami it is quite possible to predict and create unique sense keys as EWN grows.

@arademaker's comment underlines that sense keys are a Princeton design choice and that other resources may use different ID schemes for senses

**Comment by jmccrae** [comment]
Close this issue?

**Comment by goodmami** [comment]
So the resolution was there is no need for a sense key attribute, and therefore no change to the schema and any mapping of IDs across wordnet versions happens externally (meaning, the `dc:identifier` attribute usage for sense keys is an idiosyncrasy of the current EWN and not a cross-project convention)? I'm fine with that, and with closing the issue.

**Comment by jmccrae** [comment]
Closed by #38
