### ISSUE TITLE
Lexicographer File Attribute

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/schemas#26]
Should we have an attribute for lexicographer files? Is this something that many (more than one) wordnet projects use?

**Comment by arademaker** [comment]
I think it is important.

**Comment by rwingerter55** [comment]
It could be useful. Open English WordNet uses dcterms:subject (with values like "noun.act" etc.), and with an attribute for lexicographer files no information would be lost if the value of dcterms:subject is changed.

**Comment by jmccrae** [comment]
I guess the simple solution here is to have a `lexfile` attribute on the synset?

```xml
        <Synset id="example-en-10161911-n" ili="i90287" partOfSpeech="n" lexfile="noun.example">
        ...
        </Synset>
``

**Comment by goodmami** [comment]
If we go with an attribute, then what you have looks good.

If we go with a separate file for #25, it seems like this could get the same treatment as they are similar (they're for backwards compatibility, the mapping is not likely to change, they're mainly relevant for PWN-derived resources, ...).

**Comment by fcbond** [comment]
I think in this case people may add them still to new synsets (it has been on my todo list for a long time), so there is value in having them in the wordnet.

**Comment by 1313ou** [comment]
This is fine if merging is lossless.
