### ISSUE TITLE
wn.ttl

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/schemas#33]
We may consider some previous definitions from https://github.com/own-pt/openWordnet-PT/blob/master/wn30.ttl? See constraints on the relations.

**Comment by jmccrae** [comment]
We certainly could do this. Could you be more specific about which constraints you would like to import?

**Comment by arademaker** [comment]
Sorry for being so general. At this point, there are so many fundamental differences between the models that I don't know from where we can start. See screenshot. 

I was calling the attention for the restrictions on relations such as https://github.com/own-pt/openWordnet-PT/blob/master/wn30.ttl#L110-L121. But I have subtypes for the Synset class. I am assuming that the wn.ttl here was created to model the XML scheme inspired by (or adopting fully) Ontolex (based on Lemon), right? 

My model started from the https://www.w3.org/TR/wordnet-rdf/ (it precedes Lemon and Ontolex), with few changes and improvements. It is hard to compare the models because each one has its goals. My goal was to model the WN abstract model, as simple as possible (synsets, senses and word forms). 

We are trying to make a strong claim that Global Wordnet Association defines/suggests/specifies a single RDF model for encoding wordnets, which may not be true. We may decide by the current model following arguments such as the first sentence in http://john.mccr.ae/papers/mccrae2017ontolex.pdf: 

> The lemon model has become the primary mechanism for the representation of lexical data on the Semantic Web.

But I really don't know what support this claim.

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/86403/91991514-5d0f6500-ed09-11ea-9cd8-e4a4d484a3bf.png">

**Comment by jmccrae** [comment]
Okay, I am not sure what exactly you want here... There is another issue (#20) on creating support for the RDF files based on the W3C ontology, so I am happy to support you if you want to make a pull request for this.
