### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by fcbond** [globalwordnet/schemas#35]
It would be good to have tagged release with the 1.0 DTD (the version we are using for LiLT) and then maybe start a new file (WN-LMF-1.1.dtd) for the new DTD, so that people are not surprised by changes.

**Comment by jmccrae** [comment]
Yes, I plan to do this anyway.

**Comment by goodmami** [comment]
Should we redo all the current pull requests to target some WN-LMF-1.1.dtd file instead?

**Comment by jmccrae** [comment]
I will update the existing MRs before the merge :)

**Comment by jmccrae** [comment]
Closed by #38
