### ISSUE TITLE
similar vs verb_group

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/schemas#49]
The wn30.xml from https://github.com/bond-lab/omw-data/tree/main/wns/pwn30 has `similar` used in place of `verb_group` that is documented in https://globalwordnet.github.io/schemas/. The DTD files do not contain the `verb_group`:

```xml
    <Synset id="pwn-02136271-v" ili="i32435" partOfSpeech="v" dc:subject="verb.perception">
      <Definition >to throw or bend back (from a surface); &quot;Sound is reflected well in this auditorium&quot;</Definition>
      <SynsetRelation relType="domain_topic" target="pwn-06094774-n" />
      <SynsetRelation relType="similar" target="pwn-02136533-v" />
      <SynsetRelation relType="hyponym" target="pwn-02136533-v" />
      <SynsetRelation relType="hyponym" target="pwn-02766925-v" />
    </Synset>
```

**Comment by goodmami** [comment]
`similar` is also in the list of synset relations, but not in the list for senses. @arademaker are you saying that relations that are originally `verb_group` in the PWN 3.0 are replaced with `similar` for the `wn30.xml` file that Francis produces?

I was unaware of `verb_group`, probably because I'm working from the DTDs, but it has been in the documentation since at least 2016. Is it just missing from the DTDs?

**Comment by jmccrae** [comment]
We decided that similar was the name of the property that Princeton called 'verb group'. This was merged with the 'similar to' property for adjectives in PWN. It was decided that they were essentially the same thing in different part-of-speech.

**Comment by jmccrae** [comment]
It probably should! Thanks for catching this.

**Comment by arademaker** [comment]
> similar is also in the list of synset relations, but not in the list for senses. @arademaker are you saying that relations that are originally verb_group in the PWN 3.0 are replaced with similar for the wn30.xml file that Francis produces?

yes

**Comment by arademaker** [comment]
OK, so `Verb Group` is merged with `Similar to` from https://wordnet.princeton.edu/documentation/wninput5wn, right?

**Comment by arademaker** [comment]
The page https://globalwordnet.github.io/schemas/ also says that `verb_group` is a relation between senses, which is not true. The Princeton `verb group` is a relation between synsets. The name `similar to` was also simplified to `similar` only, right? But I found now in https://globalwordnet.github.io/gwadoc/#similar the comment about the merging. I believe the page https://globalwordnet.github.io/schemas/ should just point to the https://globalwordnet.github.io/gwadoc/ so we can avoid these inconsistencies.

**Comment by 1313ou** [comment]
The 'similar' relation is central to the adjective model in Princeton wordnet: it is exclusive to adjectives and tags the relation  between a core adjective (a cluster head that has an antonym) and its satellites and vice-versa. It is NOT used with another meaning (and specifically it does not hold among synset members)

here is the count:
```
similar a s	10717  (from head to satellite)
similar s a	10717  (from satellite to head)

```
a=adjective cluster head
s=satellite adjective

The 'verb_group' relation is indeed semantic (though 2 instances are lexical, probably erroneously). It looks like similarity for adjectives in that "satellites" (block up, block off, blockade, barricade, bar, stop) relate to a head (block) thus forming a verb group. But it is not a defining relation among verbs the way similarity is among adjs.

Should they be merged ? If so the new relation should not be described as a Princeton WordNet property without a caveat.

**Comment by arademaker** [comment]
I agree @1313ou. I would vote not to merge. But you are right that if I they are merged. We need to explicit declare as a different relation not from PWN.
