### ISSUE TITLE
JSON Scheme synset hasn't example

### ISSUE THREAD

**Issue by terrierscript** [globalwordnet/schemas#60]
In DTD file, Synset has example. (https://github.com/globalwordnet/schemas/blob/master/WN-LMF-relaxed-1.0.dtd#L88)

but json scheme file's Synset hasn't example field (https://github.com/globalwordnet/schemas/blob/6a8c1208891ac265e91e10cc62a2bfd87819a366/wn-json-schema-1.1.json#L339-L527)

Is this bug? or some reason?

**Comment by jmccrae** [comment]
Seems to be an oversight. I have fixed the schema.

Thanks for the report!
