### ISSUE TITLE
Synsets are inferred to be lexical entries in wordnet RDF ontology

### ISSUE THREAD

**Issue by andreabellandi** [globalwordnet/schemas#67]
Hi,
we would like to point out that according to the current definition of the property wn:partOfSpeech (which has domain ontolex:LexicalEntry), synsets with parts of speech are inferred to be of type lexical entry. This means for example that they have to have at least one lexical form which does not make sense with synsets....

Cheers,
Andrea and Fahad

**Comment by arademaker** [comment]
Good catch. This need to be solved.

**Comment by arademaker** [comment]
Synsets at PWN do not have part of speech but types... It is a common mistake to consider them the same thing. But `s` is a type and not a part of speech, the problem is that this is the only value that makes those to types different.
