### ISSUE TITLE
Add xml:space attribute for WN-LMF format

### ISSUE THREAD

**Issue by goodmami** [globalwordnet/schemas#70]
If a wordnet author wishes to ensure whitespace is preserved in things like examples, definitions, etc. in the WN-LMF format, they should use the `xml:space` attribute with the value `"preserve"`, but this attribute must be declared in the schema if it is to be used in a valid document. See https://github.com/goodmami/wn/issues/151#issuecomment-1135408720 for further discussion.

I'm not advocating for or against this attribute's inclusion as I don't know if there's a real need, but just raising the issue for discussion since it came up in https://github.com/goodmami/wn/issues/151.

**Comment by jmccrae** [comment]
Does this PR fix the issue in a way that works for you @goodmami ?

**Comment by goodmami** [comment]
@jmccrae thanks, partially, but I think I was being unclear:

> I think any free-form text might be good, I can't imagine it being useful on `<Lemma>`, `<Form>`, `<Tag>`, `<Count>`, etc.

I should have said "something to consider" instead of "good". Also, I was trying to say that we don't need it for the elements listed above. Furthermore, `<Lemma>` and `<Form>` have their values in the `writtenForm` attribute and not between the element tags, so `xml:space="preserve"` wouldn't even do the intended thing for them. For the PR, let's just stick with `<Definition>`, `<ILIDefinition>`, and `<Example>` for now.

**Comment by jmccrae** [comment]
Okay, I have updated the PR. Thanks for the comment
