### ISSUE TITLE
wn-simple TTL files missing @prefix declarations

### ISSUE THREAD

**Issue by rhdunn** [globalwordnet/schemas#73]
The `wn-simple-1.1.ttl`, `wn-simple-1.2.ttl`, and `wn-simple-1.3.ttl` files are missing the following `@prefix` annotations:

```
@prefix cc: <http://creativecommons.org/ns#> .
@prefix dc: <http://purl.org/dc/elements/1.1/> .
@prefix vann: <http://purl.org/vocab/vann/> .
@prefix voaf: <http://purl.org/vocommons/voaf#> .
```

As such, they will fail to be processed by an RDF application.

**Comment by jmccrae** [comment]
Thanks for the report, we will update this soon.
